version: '3.1'
services:
  springboot:
    build: .
    restart: always
    container_name: bootdockercontainer
    ports:
      - 8081:8081
    working_dir: /app
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
