jasypt:
  encryptor:
    algorithm: PBEWITHSHA1ANDDESEDE
    password: eicsPPK
jwt:
  header: Authorization
  prefix: Bearer
  jwtSecret: ENC(vaqyc5tn/Tdgc+JQbbIJyyNG3QrqoN2A)
  jwtExpirationInMs: 604800000
  sign-up-url: /api/auth/signin


loggin:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EICS
    username: postgres
    password: ENC(vaqyc5tn/Tdgc+JQbbIJyyNG3QrqoN2A)
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    generate-dll: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    open-in-view: false
    properties:
      hibernate :
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
        id:
          new_generator_mappings: true
        default_schema: "EICS"
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC