jasypt:
  encryptor:
    algorithm: PBEWITHSHA1ANDDESEDE
    password: bcodeDev
jwt:
  header: Authorization
  prefix: Bearer
  jwtSecret: ENC(NorQkdttHa8kUcJfuvVK/AIGPgHlsNaO2vQhs8jzNZCZDf6ji9U3qg==)
  jwtExpirationInMs: 604800000
  sign-up-url: /api/auth/signin


loggin:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop

    open-in-view: false
    properties:
      hibernate :
        jdbc:
          time_zone: UTC
        hbm2ddl:
          import_files: data-h2.sql
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
        id:
          new_generator_mappings: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

server:
  port: 8081
#  address: 127.0.0.1